# Do not add comments to this file. They will be lost.

sidebar:
  - type: section
    link: /Web/Security
  - type: section
    title: Guides
  - type: listSubPages
    path: /Web/Security/Attacks
    link: /Web/Security/Attacks
    details: closed
  - type: listSubPages
    path: /Web/Security/Defenses
    link: /Web/Security/Defenses
    details: closed
  - type: listSubPages
    path: /Web/Security/Authentication
    link: /Web/Security/Authentication
    details: closed
  - type: listSubPages
    path: /Web/Security/Practical_implementation_guides
    link: /Web/Security/Practical_implementation_guides
    title: Practical implementation guides
    details: closed
  - /Web/Security/IFrame_credentialless
  - /Web/Security/Referer_header:_privacy_and_security_concerns
  - /Web/Security/Firefox_Security_Guidelines
