name: auto-merge

on:
  pull_request_target:

# No GITHUB_TOKEN permissions, as we use AUTOMERGE_TOKEN instead.
permissions: {}

jobs:
  auto-merge:
    uses: mdn/workflows/.github/workflows/auto-merge.yml@main
    if: github.repository_owner == 'mdn'
    with:
      target-repo: ${{ github.workflow }}
    secrets:
      GH_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
