name: Update InterfaceData.json

on:
  schedule:
    # picking Fridays as webref IDL releases tend to be pushed on Thursdays
    - cron: "0 0 * * 6"
  workflow_dispatch:

# No GITHUB_TOKEN permissions, as we use AUTOMERGE_TOKEN instead.
permissions: {}

jobs:
  update:
    if: github.repository == 'mdn/content'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          path: mdn-content
          ref: main
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: "mdn-content/.nvmrc"
          package-manager-cache: false

      - name: Checkout webref
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: w3c/webref
          path: webref
          ref: "@webref/idl@latest"
          persist-credentials: false

      - name: Extract data from webref
        working-directory: mdn-content
        run: node scripts/update-interface-data.js ../webref/

      - name: Create pull request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          path: mdn-content
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          title: Update InterfaceData based on WebRef
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          commit-message: Update InterfaceData based on WebRef
          body: Automated changes generated by scripts/update-interface-data via interface-updater github workflow
          labels: |
            automated pr
          delete-branch: true
          branch: interfacedata-update
