name: Check Redirects

on:
  pull_request:

# No GITHUB_TOKEN permissions, as we only use it to increase API limit.
permissions: {}

jobs:
  check-redirects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      # This is a "required" workflow so path filtering can not be used:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      # We have to rely on a custom filtering mechanism to run the checks only if required files are modified.
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        name: See if any file needs checking
        id: filter
        with:
          filters: |
            required_files:
              - ".nvmrc"
              - "files/**"
              - ".github/workflows/pr-check_redirects.yml"

      - name: Install
        if: steps.filter.outputs.required_files == 'true'
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check redirects file(s)
        if: steps.filter.outputs.required_files == 'true'
        run: npm run content validate-redirects en-US
        env:
          # Used by the `rari` cli to avoid rate limiting issues
          # when fetching the latest releases info from the GitHub API.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
