name: Check scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - .nvmrc
      - package.json
      - yarn.lock
      - .github/workflows/pr-check_scripts.yml

jobs:
  up-to-date-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: yarn install
        run: yarn --frozen-lockfile

      - run: yarn up-to-date-check

  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: yarn install
        run: yarn --frozen-lockfile

      - name: yarn start
        run: yarn start > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Wait for server
        run: |
          # Just a slight delay to wait until the dev server is ready.
          sleep 3

          curl --retry-connrefused --retry 5 http://localhost:5042 > /dev/null

          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink > /dev/null
          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink/index.json > /dev/null

      - name: Debug server's stdout and stderr if tests failed
        if: failure()
        run: |
          echo "STDOUT..................................................."
          cat /tmp/stdout.log
          echo ""
          echo "STDERR..................................................."
          cat /tmp/stderr.log

  filecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: yarn install
        run: yarn --frozen-lockfile

      - run: yarn filecheck --help

  content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - run: yarn content --help

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: yarn install
        run: yarn --frozen-lockfile

      - run: yarn build --help
