name: Check cSpell lists

on:
  pull_request:
    paths:
      - .vscode/dictionaries/*

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .vscode/dictionaries/*
            .nvmrc
            package.json
            scripts/sort_and_unique_file_lines.js
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Check if cSpell word lists are in correct order
        run: |
          node scripts/sort_and_unique_file_lines.js --check .vscode/dictionaries
