name: Check scripts

on:
  pull_request:
    paths:
      - .nvmrc
      - package.json
      - package-lock.json
      - .github/workflows/pr-check_scripts.yml

# No GITHUB_TOKEN permissions, as we only use it to increase API limit.
permissions: {}

jobs:
  up-to-date-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: npm ci
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run up-to-date-check

  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: npm ci
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: npm start
        run: npm start > /tmp/stdout.log 2> /tmp/stderr.log &
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Rari (localhost:8083)
        run: curl --retry-connrefused --retry 5 -I http://localhost:8083/en-US/

      - name: Test Fred (localhost:5042)
        run: |
          curl --retry-connrefused --retry 5 http://localhost:5042 > /dev/null

          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink > /dev/null
          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink/index.json > /dev/null

      - name: Debug server's stdout and stderr if tests failed
        if: failure()
        run: |
          echo "STDOUT..................................................."
          cat /tmp/stdout.log
          echo ""
          echo "STDERR..................................................."
          cat /tmp/stderr.log

  filecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: npm ci
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run filecheck -- --help

  content:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run content -- --help

      - run: npm run content fix-redirects en-US

      - run: npm run content validate-redirects en-US

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: npm ci
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run build -- --help
