name: Check URL issues

on:
  pull_request:
    paths:
      - "files/**/*.md"

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  check_url_issues:
    #if: github.repository == 'mdn/content'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Check URL deletions and broken fragments
        run: |
          echo "::add-matcher::.github/workflows/url-issues-problem-matcher.json"
          git fetch origin main
          node scripts/log-url-issues.js --workflow
