# Checks the PR itself for hygiene things.

name: PR Lint

on:
  pull_request:
    # Necessary to re-run if someone edits the PR without a new pushed commit.
    types: [opened, edited, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - name: Install all yarn packages
        working-directory: pr-lint
        run: yarn --frozen-lockfile

      - name: Run checks
        working-directory: pr-lint
        run: yarn run check
