name: Preview

on:
  pull_request:
    paths:
      - package.json
      - yarn.lock
      - .github/workflows/preview.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "12"
          cache: yarn

      - name: Install all yarn packages
        run: |
          yarn --frozen-lockfile

      - name: Start the Yari server
        run: |
          yarn start &

      - name: Wait for server
        run: |
          curl --retry-connrefused --retry 5 http://localhost:5042

          # TODO Do something with puppeteer here maybe

          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink > /dev/null
          curl --fail http://localhost:5042/en-US/docs/MDN/Kitchensink/index.json > /dev/null
